
  version: '3.8'

  networks:
      my_adhocproject_network:
        external:  true

  services:
    containerize_app_1:
        build:
          context: ./
          dockerfile: Dockerfile
        expose: 
            - 8000
        image: flask_app
        container_name: containerize_app_1
        volumes:
              - ./:/my_projectadhoc
       # enviornment:
        #- CONTAINERIZE_APP_1=/my_projectadhoc/project.py
       # command: flask run --host==0.0.0.0
       # networks:
       #   my_adhocproject_network:
       # aliases:
        #    - containerize_app_1
        ports:
            - 8000:8000
        networks:
            my_adhocproject_network:
    redis_app:
        image: redis:latest
        command: redis-server --requirepass add_password_here
        expose:
        - 6379
        ports:
        - 6000:6379
        networks:
        - my_adhocproject_network
  
    nginx:
        image: nginx
        container_name: containerize_nginx_1
        depends_on:
        - containerize_app_1
        volumes:
        #- ./nginx.conf:/etc/nginx/conf.d/default.conf
        -  ./run/desktop/mnt/host/c/User/rendo/desktop/my_projectadhoc/conf.d/default.conf
        #-  ./conf.d/proxydefault.conf:/etc/nginx/conf.d/proxydefault.conf
        -  ./ssl/localhost.key:/etc/nginx/files/localhost.key
        -  ./ssl/localhost.crt:/etc/nginx/files/localhost.crt
        -  ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
        #- ./ssl/.:/etc/nginx/files/
        #-  ./conf.d/proxydefault.conf:/etc/nginx/sites-available/proxydefault.conf
        #- ./ssl/localhost.crt:/etc/nginx/files/
        #- ./run/desktop/mnt/host/c/User/rendo/desktop/Users/rendo/Desktop/my_projectadhoc/ssl/localhost.crt:/etc/nginx/files/localhost.crt
        #- ./run/desktop/mnt/host/c/User/rendo/desktop/Users/rendo/Desktop/my_projectadhoc/ssl/localhost.key:/etc/nginx/files/localhost.key
        #- ./conf.d:/etc/nginx/conf.d/default.conf
        ports:
        - "8080:80"
        - "443:443"
        networks:
        - my_adhocproject_network

        #networks:
           # my_adhocproject_network:
           # external: true

